[package]
authors.workspace    = true
description          = "Utilities to create PHP AST for biome_php_parser"
documentation        = "https://docs.rs/biome_php_factory"
edition.workspace    = true
license.workspace    = true
name                 = "biome_php_factory"
repository.workspace = true
version              = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_php_syntax = { workspace = true }
biome_rowan     = { workspace = true }

[lints]
workspace = true