[package]
edition = "2021"
name    = "biome_v8"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow   = "1.0.57"
serde    = { workspace = true }
serde_v8 = { version = "0.108.0" }
v8       = { version = "0.74.3", default-features = false }

biome_js_factory = { workspace = true }
biome_js_syntax  = { workspace = true }
biome_rowan      = { workspace = true, features = ["serde"] }

[dev-dependencies]
bpaf             = { workspace = true }
crossbeam        = { workspace = true }
biome_console     = { workspace = true }
biome_diagnostics = { workspace = true }
biome_fs          = { workspace = true }
biome_js_parser   = { workspace = true }
biome_service     = { workspace = true }

[build-dependencies]
biome_idl = { path = "../biome_idl" }
